const champions = [
  {
    nom: "Yasuo",
    role: "Combattant / Assassin",
    icon: "assets/champ-icons/yasuo.png",
    difficulte: "Difficile",
    description: "Un samouraï errant qui contrôle le vent.",
    build: [
      {
        nom: "Lame d'infini",
        icon: "assets/items-icons/lame-d'infinie.png",
      },
      "Danseur fantôme",
      "Coupeur d'os immortel",
      "Mort du danseur",
      "Ange gardien",
    ],
  },
  {
    nom: "Lux",
    role: "Mage / Support",
    difficulte: "Facile",
    description: "Une magicienne de la lumière de Demacia.",
    build: [
      "Luminescence de Luden",
      "Chapeau de Rabadon",
      "Bâton du vide",
      "Sablier de Zhonya",
      "Orbe de la morellenomicon",
    ],
  },
  {
    nom: "Garen",
    role: "Tank / Combattant",
    difficulte: "Facile",
    description: "Le fier guerrier de Demacia, simple mais efficace.",
    build: [
      "Fendeur de Stridebreaker",
      "Mort du danseur",
      "Plate de Sterak",
      "Armure de Randuin",
      "Force de la nature",
    ],
  },
  {
    nom: "Jinx",
    role: "Tireur",
    difficulte: "Moyen",
    description: "Une criminelle surexcitée fan de chaos et d'explosions.",
    build: [
      "Kraken Slayer",
      "Ouragan de Runaan",
      "Lame d'infini",
      "Rappel de Lord Dominik",
      "Danse de la mort",
    ],
  },
  {
    nom: "Thresh",
    role: "Support / Tank",
    difficulte: "Difficile",
    description: "Le geôlier spectral qui collecte les âmes.",
    build: [
      "Mélodie spectrale",
      "Armure de Zeke",
      "Vœu du chevalier",
      "Cœur de glace",
      "Rédemption",
    ],
  },
  {
    nom: "Ahri",
    role: "Mage / Assassin",
    difficulte: "Moyen",
    description: "Une renarde à neuf queues, charmeuse et mortelle.",
    build: [
      "Luminescence de Luden",
      "Chapeau de Rabadon",
      "Sablier de Zhonya",
      "Hextèque de rocketbelt",
      "Bâton du vide",
    ],
  },
  {
    nom: "Darius",
    role: "Combattant / Tank",
    difficulte: "Moyen",
    description: "Le bourreau de Noxus. Un dunk et c'est fini.",
    build: [
      "Hache noire",
      "Fendeur de Stridebreaker",
      "Plate de Sterak",
      "Cœur de glace",
      "Ange gardien",
    ],
  },
  {
    nom: "Zed",
    role: "Assassin",
    difficulte: "Difficile",
    description: "Le maître des ombres, furtif et mortel.",
    build: [
      "Eclipse",
      "Lame du collectionneur",
      "Rancune de Serylda",
      "Lame d'infini",
      "Danse de la mort",
    ],
  },
];
